server:
  undertow:
    accesslog:
      dir: ./logs
      enabled: true
      prefix: ${spring.application.name}
  port: 9081
  servlet:
    context-path: /${spring.application.name}

spring:
  application:
    #服务名称
    name: service-demo
    #使用@project.version@，可以自动从pom文件中获取项目版本号
    version: '@project.version@'
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  resources:
    #静态文件路径,多模块使用classpath*表示路径
    static-locations: classpath:/static/,classpath*:/META-INF/resources/

logging:
  config: classpath:META-INF/logback-${spring.profiles.active}.xml
  file:
    max-size: 50MB
    max-history: 3

#swagger
bt:
  swagger:
    title: ${spring.application.name}
    description: Demo 示例
    version: ${spring.application.version}

